import psycopg2
from rinet_db_config import get_connection


connection = get_connection()
cursor = connection.cursor()

try:

    # Base tables. IF NOT EXISTS makes these safe to re-run on every script execution.
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS staff(
            id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 101) PRIMARY KEY,
            last_name VARCHAR(20) NOT NULL,
            first_name VARCHAR(20) NOT NULL,
            gender VARCHAR(10) CHECK (gender IN ('Male','Female'))
        )
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS attendance(
            id SERIAL PRIMARY KEY,
            staff_id INT REFERENCES staff(id),
            attendance_date DATE DEFAULT CURRENT_DATE,
            sign_in_time TIME
        )
        """
    )


    # Postgres has no "ADD CONSTRAINT IF NOT EXISTS" syntax, so instead we:
    # 1. Mark a SAVEPOINT before the risky statement.
    # 2. Try to add the constraint.
    # 3. If it already exists, Postgres errors out AND poisons the whole transaction (every statement after it would fail too) unless we roll back to the savepoint, which undoes just this one statement.
    # Two exception types can show up here for the same "already exists" case:
    # - DuplicateObject  (42710): the constraint itself already exists.
    # - DuplicateTable   (42P07): a UNIQUE constraint auto-creates a backing index with the same name as the constraint. If that index name is already taken (e.g. from the first time this ran), Postgres complains about the relation/index, not the constraint, so we catch this too.

    cursor.execute("SAVEPOINT sp_unique_identification")
    try:
        cursor.execute(
            """
            ALTER TABLE staff ADD CONSTRAINT unique_identification UNIQUE(last_name, first_name, gender)
            """
        )

        # No error -> keep the change, forget the savepoint.
        cursor.execute("RELEASE SAVEPOINT sp_unique_identification")
    except (psycopg2.errors.DuplicateObject, psycopg2.errors.DuplicateTable):
        # Constraint already exists -> undo just this statement, transaction stays usable.
        cursor.execute("ROLLBACK TO SAVEPOINT sp_unique_identification")

    cursor.execute("SAVEPOINT sp_unique_attendance")
    try:
        cursor.execute(
            """
            ALTER TABLE attendance ADD CONSTRAINT unique_attendance UNIQUE(staff_id, attendance_date, sign_in_time)
            """
        )
        cursor.execute("RELEASE SAVEPOINT sp_unique_attendance")
    except (psycopg2.errors.DuplicateObject, psycopg2.errors.DuplicateTable):
        cursor.execute("ROLLBACK TO SAVEPOINT sp_unique_attendance")


    # Commits table creation + whichever constraints were newly added this run.
    connection.commit()
    
finally:
    # Always release DB resources, even if something above raised an exception we didn't explicitly catch.
    cursor.close()
    connection.close()



